// scripted pipeline
node {
    checkout scm // ambil repository terbaru

    docker.image('my-python-ci').inside() {
        
        env.CI = 'true'

        stage('Build') {
            sh '''
            echo "=== DEBUG START ==="
            pwd
            ls -R
            cat test-reports/results.xml || echo "NO REPORT FILE"
            echo "=== DEBUG END ==="
            '''
            sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
        } // end of stage build
        
        if (currentBuild.result == 'UNSTABLE') return
        

        stage('Test') {
            try {
                sh '''
                mkdir -p test-reports
                pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py
                '''
            } finally {
                junit 'test-reports/results.xml'
            }
        } // end of stage test
        
        if (currentBuild.result == 'UNSTABLE') return


        // stage('Deliver') {
        //     try {
        //         sh 'pip install pyinstaller'
        //         sh 'pyinstaller --onefile sources/add2vals.py'

        //         archiveArtifacts 'dist/add2vals'
        //     } catch(err) {
        //         currentBuild.result = 'FAILURE'
        //         throw err
        //     }
        // } // end of stage deliver
        
        if (currentBuild.result == 'UNSTABLE') return
    } // end of dockerImage
}
