// scripted pipeline
node {
    stage('Build') {
        sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
    }

    if (currentBuild.result == 'UNSTABLE') return
    
    stage('Test') {
        try {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        } finally {
            junit 'test-reports/results.xml'
        }
    }

    if (currentBuild.result == 'UNSTABLE') return

    stage('Deliver') {
        try {
            sh 'pyinstaller --onefile sources/add2vals.py'

            archiveArtifacts 'dist/add2vals'
        } catch(err) {
            currentBuild.result = 'FAILURE'
            throw err
        }
    }

    if (currentBuild.result == 'UNSTABLE') return
}
