// scripted pipeline
node {

    cleanWs() // bersihkan workspace
    checkout scm // ambil repository terbaru

    def dockerImage = docker.build('my-python-ci', './python-ci') // build image python di jenkins
    dockerImage.inside() {
        
        env.CI = 'true' // atur environment

        // Stage: Debug
        stage('Debug'){
            sh '''
            echo "=== DEBUG START ==="
            pwd
            ls -R
            cat test-reports/results.xml || echo "NO REPORT FILE"
            echo "=== DEBUG END ==="
            '''
        }


        // Stage: Build
        stage('Build') {
            sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
        }
        if (currentBuild.result == 'UNSTABLE') return
        

        // Stage: Test
        stage('Test') {
            try {
                sh '''
                mkdir -p test-reports
                pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py
                '''
            } finally {
                junit 'test-reports/results.xml'
            }
        }
        if (currentBuild.result == 'UNSTABLE') return


        // Stage: Deliver
        stage('Deliver') {
            try {
                sh 'pyinstaller --onefile sources/add2vals.py'

                archiveArtifacts 'dist/add2vals'
            } catch(err) {
                currentBuild.result = 'FAILURE'
                throw err
            }
        }
        if (currentBuild.result == 'UNSTABLE') return
        
    } // end of dockerImage
}
